//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aksesuar
    {
        public int Id { get; set; }
        public string AksesuarAdi { get; set; }
        public string AksesuarKodu { get; set; }
        public string AksesuarGorsel { get; set; }
        public string AksesuarKalipNo { get; set; }
        public string AksesuarBirim { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<bool> Motor { get; set; }
        public Nullable<bool> Kumanda { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
