//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamKombinasyon
    {
        public int Id { get; set; }
        public string Kombinasyon { get; set; }
        public string Birim { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
    }
}
