//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CamSistemModel : DbContext
    {
        public CamSistemModel()
            : base("name=CamSistemModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Aksesuar> Aksesuar { get; set; }
        public virtual DbSet<AltSistem> AltSistem { get; set; }
        public virtual DbSet<AtikStok> AtikStok { get; set; }
        public virtual DbSet<BoyaTedarik> BoyaTedarik { get; set; }
        public virtual DbSet<CamKombinasyon> CamKombinasyon { get; set; }
        public virtual DbSet<CamTedarik> CamTedarik { get; set; }
        public virtual DbSet<DisSiparis> DisSiparis { get; set; }
        public virtual DbSet<DisTedarik> DisTedarik { get; set; }
        public virtual DbSet<Durum> Durum { get; set; }
        public virtual DbSet<ImalatDurum> ImalatDurum { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<OptimizasyonHesap> OptimizasyonHesap { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<ProfilBoy> ProfilBoy { get; set; }
        public virtual DbSet<Renk> Renk { get; set; }
        public virtual DbSet<Sabitler> Sabitler { get; set; }
        public virtual DbSet<Sevkiyat> Sevkiyat { get; set; }
        public virtual DbSet<SevkiyatPaket> SevkiyatPaket { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisAksesuar> SiparisAksesuar { get; set; }
        public virtual DbSet<SiparisCam> SiparisCam { get; set; }
        public virtual DbSet<SiparisEnBoyAdet> SiparisEnBoyAdet { get; set; }
        public virtual DbSet<SiparisSevkiyatAksesuar> SiparisSevkiyatAksesuar { get; set; }
        public virtual DbSet<SiparisSevkiyatProfil> SiparisSevkiyatProfil { get; set; }
        public virtual DbSet<SiparisStok> SiparisStok { get; set; }
        public virtual DbSet<SiparisTeklif> SiparisTeklif { get; set; }
        public virtual DbSet<SiparisTeklifToplamBilgisi> SiparisTeklifToplamBilgisi { get; set; }
        public virtual DbSet<Sistem> Sistem { get; set; }
        public virtual DbSet<SistemAksesuarJoin> SistemAksesuarJoin { get; set; }
        public virtual DbSet<SistemAltSistemJoin> SistemAltSistemJoin { get; set; }
        public virtual DbSet<SistemProfilJoin> SistemProfilJoin { get; set; }
        public virtual DbSet<SistemTur> SistemTur { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<StokAksesuar> StokAksesuar { get; set; }
        public virtual DbSet<Tedarikci> Tedarikci { get; set; }
        public virtual DbSet<YuklenenDosyalar> YuklenenDosyalar { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolSayfaYetki> RolSayfaYetki { get; set; }
        public virtual DbSet<Sayfa> Sayfa { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
    }
}
