//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamTedarik
    {
        public long Id { get; set; }
        public Nullable<int> TedarikciId { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public Nullable<System.DateTime> SiparisOnayTarihi { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public string GuncelDurum { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string DosyaIds { get; set; }
    }
}
