//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisSiparis
    {
        public int Id { get; set; }
        public Nullable<long> MusteriId { get; set; }
        public string FisNo { get; set; }
        public Nullable<int> DurumId { get; set; }
        public string SistemBilgisi { get; set; }
        public string SistemAciklamasi { get; set; }
        public string IslemDurum { get; set; }
        public string GenelAciklama { get; set; }
        public Nullable<System.DateTime> OnayIptalTarihi { get; set; }
        public Nullable<int> OnayIptalKullaniciId { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<int> TedarikciId { get; set; }
        public Nullable<decimal> TedarikFiyat { get; set; }
        public string SiparisAciklama { get; set; }
        public Nullable<long> SevkiyatId { get; set; }
    }
}
