//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisTedarik
    {
        public long Id { get; set; }
        public Nullable<int> TedarikciId { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public string SistemBilgisi { get; set; }
        public Nullable<System.DateTime> TedarikTarihi { get; set; }
        public Nullable<decimal> TedarikFiyat { get; set; }
        public string SistemAciklama { get; set; }
        public string GenelAciklama { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string DosyaIds { get; set; }
    }
}
