//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptimizasyonHesap
    {
        public long Id { get; set; }
        public string SiparisIds { get; set; }
        public Nullable<int> ProfilId { get; set; }
        public Nullable<int> ProfilBoy { get; set; }
        public string KesilecekOlculer { get; set; }
        public Nullable<int> KesimAdet { get; set; }
        public Nullable<int> FireAtik { get; set; }
        public Nullable<decimal> ToplamAtikUzunluk { get; set; }
        public Nullable<decimal> ToplamAtikAgirlik { get; set; }
        public Nullable<decimal> FireyeEklenenToplamUzunluk { get; set; }
        public Nullable<decimal> FireyeEklenenToplamAgirlik { get; set; }
        public Nullable<decimal> AsilStoktanKullanilanToplamUzunluk { get; set; }
        public Nullable<decimal> AsilStoktanKullanilanToplamAgirlik { get; set; }
        public Nullable<decimal> FiredenKullanilanToplamUzunluk { get; set; }
        public Nullable<decimal> FiredenKullanilanToplamAgirlik { get; set; }
        public string KullanilanAlan { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<bool> ImalatDurum { get; set; }
    }
}
