//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilBoy
    {
        public int Id { get; set; }
        public Nullable<int> ProfilBoyu { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
