//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SevkiyatPaket
    {
        public long Id { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public Nullable<int> PaketEn { get; set; }
        public Nullable<int> PaketBoy { get; set; }
        public Nullable<int> PaketYukseklik { get; set; }
        public Nullable<int> PaketAdet { get; set; }
    }
}
