//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevkiyat
    {
        public int Id { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public string SevkiyatBilgisi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> SevkiyatTarihi { get; set; }
        public string DosyaIds { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    }
}
