//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTeklif
    {
        public long Id { get; set; }
        public Nullable<long> SiparisEnBoyAdetId { get; set; }
        public string Malzeme { get; set; }
        public string Birim { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
