//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisEnBoyAdet
    {
        public long Id { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public Nullable<int> GirilenEn { get; set; }
        public Nullable<int> GirilenSolEn { get; set; }
        public Nullable<int> GirilenBoy { get; set; }
        public Nullable<int> GirilenAdet { get; set; }
        public Nullable<int> GirilenKanatAdet { get; set; }
        public Nullable<int> GirilenEn3 { get; set; }
        public Nullable<int> SistemId { get; set; }
        public Nullable<int> AltSistemId { get; set; }
        public Nullable<int> SistemTurId { get; set; }
        public string KasaTipi { get; set; }
    }
}
