//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisStok
    {
        public long Id { get; set; }
        public Nullable<long> SiparisId { get; set; }
        public Nullable<int> ProfilId { get; set; }
        public Nullable<int> ProfilBoyId { get; set; }
        public Nullable<int> ProfilAdet { get; set; }
        public Nullable<int> AksesuarId { get; set; }
        public Nullable<int> AksesuarAdet { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public string Aciklama { get; set; }
        public string IslemDurum { get; set; }
        public string FisNo { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
