//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisSevkiyatProfil
    {
        public long Id { get; set; }
        public Nullable<long> SiparisEnBoyAdetId { get; set; }
        public Nullable<int> ProfilId { get; set; }
        public Nullable<decimal> ProfilBoy { get; set; }
        public Nullable<int> ProfilAdet { get; set; }
        public Nullable<decimal> ToplamMetre { get; set; }
        public Nullable<decimal> ToplamKg { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> Paket { get; set; }
    }
}
