//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTeklifToplamBilgisi
    {
        public long Id { get; set; }
        public Nullable<long> SiparisEnBoyAdetId { get; set; }
        public Nullable<decimal> ToplamMaliyet { get; set; }
        public Nullable<decimal> m2 { get; set; }
        public Nullable<decimal> Teklif { get; set; }
    }
}
