//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public long Id { get; set; }
        public Nullable<long> MusteriId { get; set; }
        public Nullable<int> SistemId { get; set; }
        public Nullable<int> SistemTurId { get; set; }
        public Nullable<int> AltSistemId { get; set; }
        public Nullable<int> RenkId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public string IslemDurum { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> TahminiTeslim { get; set; }
        public Nullable<System.DateTime> OnayIptalTarihi { get; set; }
        public Nullable<int> OnayIptalKullaniciId { get; set; }
        public string SiparisTur { get; set; }
        public Nullable<int> MotorMarkaId { get; set; }
        public Nullable<int> KumandaMarkaId { get; set; }
        public string FisNo { get; set; }
        public string Aciklama { get; set; }
        public Nullable<long> CamTedarikId { get; set; }
        public Nullable<long> BoyaTedarikId { get; set; }
        public Nullable<long> DisTedarikId { get; set; }
        public Nullable<decimal> SistemBirimFiyat { get; set; }
        public Nullable<int> ToplamAluKg { get; set; }
        public Nullable<decimal> ToplamAluKgFiyat { get; set; }
        public string DosyaIds { get; set; }
        public string ImalatDurum { get; set; }
        public Nullable<int> OlusturanKullaniciId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
