//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemAltSistemJoin
    {
        public int Id { get; set; }
        public Nullable<int> SistemId { get; set; }
        public Nullable<int> SistemTurId { get; set; }
        public Nullable<int> AltSistemId { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
