//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamSistemDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YuklenenDosyalar
    {
        public long Id { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaUzantisi { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> YuklenmeTarihi { get; set; }
    }
}
